app = "chamadosbug"  # Nome da sua aplicação no Fly.io
primary_region = "gru"  # Região (São Paulo - GRU)

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 1000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1